-- 036_org_safina_ec_key.sql
--
-- Each organization gets its own Safina EC private key. Without this
-- column every tenant signs requests with the single global env-key
-- — making them all the same Safina-side customer, no real isolation
-- with the custody provider.
--
-- The column is nullable: an org without a per-tenant key falls back
-- to the global SAFINA_EC_PRIVATE_KEY env var (legacy / development).
--
-- For prod tenants this column will hold a key generated by us per
-- onboarding, ideally rotated and stored in KMS rather than plain
-- text — see signer_backends.py for the KMS path. Plain-text storage
-- here is the same security level as the env var we have today; it's
-- not a downgrade, just makes the key per-tenant addressable.

ALTER TABLE public.organizations
    ADD COLUMN IF NOT EXISTS safina_ec_private_key text;

COMMENT ON COLUMN public.organizations.safina_ec_private_key IS
    'Per-tenant EC private key for Safina API signing (0x-prefixed hex). '
    'NULL = fall back to global SAFINA_EC_PRIVATE_KEY env.';
